[package]
name = "parser_simple"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
gamedata_scanner_models = { path = "../models" }
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.26"
regex = "1.11.1"
tempfile = "3.19.0" 